### ISSUE TITLE
アセンブラについて

### ISSUE THREAD

**Issue by nakane11** [nakane11/jishupro#10]
@kindsenior
1. 関数の引数はintの場合edi, esi, edx, ecxの順にレジスタに入ると思うのですがkeyboard関数の使われていない[edi](https://github.com/kindsenior/jishupro-nakane11/blob/d4a11596120a669e6d3ab595fa145127f2209c88/glview/main_no-initialize.s#L796) には何か入っているのでしょうか
2. shaking(), getWorldCood(), display()の最後の[__stack_chk_fail](https://github.com/kindsenior/jishupro-nakane11/blob/d4a11596120a669e6d3ab595fa145127f2209c88/glview/main_no-initialize.s#L213-L216) は、関数内のどのような処理からスタック破壊の可能性があると判断されているのでしょうか

**Comment by kindsenior** [comment]
処理を追う必要なさそうなのでとりあえず1だけ

アキュムレータレジスタの構造は[ここ](https://ja.wikibooks.org/wiki/X86%E3%82%A2%E3%82%BB%E3%83%B3%E3%83%96%E3%83%A9/x86%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3)のようになっていて，
RAX,EAX,AX,AH,ALは別のレジスタというわけではなく，一つのアキュムレータレジスタへのアクセスする領域が違う仕組みになっています
ここでのポイントはALはEAXの下位1Byteと等価であることです

第1引数のkeyはchar型で1Byteなので，
第1引数が格納されるediの下位1Byteを取り出すために，
[ediを一旦eaxに入れて](https://github.com/kindsenior/jishupro-nakane11/blob/d4a11596120a669e6d3ab595fa145127f2209c88/glview/main_no-initialize.s#L796)から[al（eaxの下位1Byteに相当）をスタック領域に入れる](https://github.com/kindsenior/jishupro-nakane11/blob/d4a11596120a669e6d3ab595fa145127f2209c88/glview/main_no-initialize.s#L799)という処理になっています
なのでediを使わないわけではなく下位1Byteにchar keyを含んだ値が入っているということになります

2は時間あるときに見てみます

**Comment by nakane11** [comment]
すみません勉強不足でした．．．
ありがとうございます

2の方もSSPについて調べ直したら, 関数内で配列の構造体あるいは[配列が宣言されている場合に挿入される]( https://github.com/nakane11/note/blob/main/x86_assembler.md#:~:text=%E6%A7%8B%E6%88%90%EF%BC%88%E7%B7%A8%E9%9B%86%E4%B8%AD%EF%BC%89-,%E3%82%B9%E3%82%BF%E3%83%83%E3%82%AF%E7%A0%B4%E5%A3%8A%E6%A4%9C%E5%87%BA,-canary%2C%20SSP(Stack )ことがわかり、実際に宣言だけ行う関数を作って確認できました。

**Comment by kindsenior** [comment]
すばらしい！
解決して良かったです！
